all:
	gcc -std=c99 -Wall parsing.c mpc.c -ledit -lm -o parsing
between:
	gcc -std=c99 -Wall parsing_between.c mpc.c -ledit -lm -o parsing_between
rab:
	gcc -std=c99 -Wall regex_allab.c mpc.c -ledit -lm -o regex_allab
rppr:
	gcc -std=c99 -Wall regex_ppr.c mpc.c -ledit -lm -o regex_ppr